### ISSUE TITLE
emacs-workspaces/kill-buffers-close-workspace is looping infinitely

### ISSUE THREAD

**Issue by mfiano** [mclear-tools/tabspaces#1]
With a workspace containing 3 buffers, `space.lisp`, `conditions.lisp`, and `*scratch*`, this function loops infinitely until Emacs crashes.

I am not that great at debugging elisp code, but writing the current buffer name and the return values of `kill-buffer` to a file results in the following until Emacs hard-crashes:

```
space.lisp	t
space.lisp	t
 *Minibuf-1*	t
space.lisp	t
 *Minibuf-1*	t
conditions.lisp	t
space.lisp	t
 *Minibuf-1*	t
conditions.lisp	t
*scratch*	t
```

It seems that even though the buffer is successfully killed, it keeps coming back.

I am using project.el, and `(project-kill-buffers t)` works flawlessly, and also seems to close the tab when the last buffer is killed, so I'm using that for now, as I couldn't debug the problem any further.

**Comment by mclearc** [comment]
Interesting. I haven't seen this problem myself and I use this function all the time. Have you checked whether this happens in a bare config (i.e. with `emacs -Q`)?

**Comment by mfiano** [comment]
Unfortunately, I haven't. I will have to come back to this problem some other time, as I spent far too long trying to debug it, and I have a temporary work-around for now. I'll post any progress I discover here as I do, if nobody else encounters it/solves it in the meantime.

**Comment by mclearc** [comment]
I just pushed a [small change](https://github.com/mclear-tools/emacs-workspaces/commit/2c68d8c36fb0c456fa795dbdb1d8c621a4965b0d) that might help. Or it might be due to something else in your config. In any case I'll leave the issue open for awhile.

**Comment by mfiano** [comment]
I do have a theory though. There might be shared structure with the original buffer list in `emacs-workspaces--buffer-list-all`, such that when a new buffer is created, the changes get picked up in the cons cells this function returns. A copy of that tree might do as a work-around.

**Comment by mfiano** [comment]
I just tried `emacs -Q` and requiring just `emacs-workspaces` and `project`, I cannot reproduce the problem, so perhaps this is not this package's problem. I'll have to dig deeper and see which package is to blame and figure out the appropriate patch some other time. I'm also not sure if this issue should be closed yet, as it's very unclear to me what is affecting this. I'll have to bisect my configuration and see what I can figure out when I have time.

**Comment by mclearc** [comment]
Sounds good -- especially since I'm unable to reproduce the problem so far!

**Comment by mclearc** [comment]
Any updates @mfiano ?

**Comment by mfiano** [comment]
Sorry no, I was never able to figure out what the problem was. Since I can't reproduce with `emacs -Q` I would say this isn't this package's fault, but just an incompatibility between some other package due to the global nature of Emacs. For that reason, I will close this issue now. Thanks for your work!
