### ISSUE TITLE
advise tab-bar-new-tab?

### ISSUE THREAD

**Issue by aaronjensen** [mclear-tools/tabspaces#12]
Would it make sense to advise `tab-bar-new-tab`, rather than providing a separate `tabspaces-create-workspace` function? If that were done, then things like `tab-bar-switch-to-tab` could be used out of the box, rather than `tabspaces-switch-to-or-create-workspace`.

**Comment by mclearc** [comment]
In general I'm reticent to use advice if I can code up something relatively small. With advice this means that one would have to turn off tabspaces mode to get the normal behavior from tab-bar, rather than having that exist alongside. Maybe that is overly cautious but 🤷‍♂️

**Comment by aaronjensen** [comment]
Yeah, I hear you. In this instance, there really should be a hook invoked when creating a new tab. That would allow a non-advice extension point, but I don't know if they would want that. I'll raise it on emacs-devel. In the interim, what would you think about putting the buffer isolation part into its own function so one could use it to advise `tab-bar-new-tab` if one so desired?

**Comment by mclearc** [comment]
> what would you think about putting the buffer isolation part into its own function so one could use it to advise tab-bar-new-tab if one so desired?

Yeah that seems like a good compromise in the meantime. If you wanna open another pull request I'll merge it.

**Comment by aaronjensen** [comment]
Thanks for the quick merging and collaboration, much appreciated. If I end up advising, I'll share the snippet so it can be added to the readme in case anyone wants that.

**Comment by mclearc** [comment]
Sounds great -- thanks for your contributions!

**Comment by aaronjensen** [comment]
Looks like there is already a hook for this:

```el
(defun tabspaces--tab-post-open-function (_tab)
  "Reset buffer list on new tab creation."
  (tabspaces-reset-buffer-list))

(add-to-list 'tab-bar-tab-post-open-functions #'tabspaces--tab-post-open-function)
```

With this in place, there is no need to advise anything or define commands like `tabspaces-create-workspace`, every new tab will have its own workspace. I'm not sure if that would be what you are looking for, but I think it's what I'm looking for in that I just want to be able to use tabs and have them each manage their own buffer list. 

I think, for now, I will experiment with a trimmed down version of tabspaces that uses this technique and see how I like it in practice.

**Comment by mclearc** [comment]
Cool -- I'll try this as well and see.

**Comment by mclearc** [comment]
FYI -- I've made a bunch of changes and simplifications starting with commit d883bafaaffa2af099e5e66939e9439aced14898

**Comment by aaronjensen** [comment]
Looks great, I’ll try it out shortly.

**Comment by aaronjensen** [comment]
Just migrated over, seems to work great. Thanks for making those updates, it's nice to have a more "vanilla" tab bar configuration now.
