### ISSUE TITLE
Saving tabspaces isolated buffer lists with desktop.el

### ISSUE THREAD

**Issue by appleinario** [mclear-tools/tabspaces#18]
**Using the functions desktop-save and desktop-revert (or with desktop+, desktop+-create and desktop+-load) doesn't save the complete buffer lists isolated within workspaces.** It does save the workspaces created across frames, and the visible buffers each workspaces--it just fails to save the list of buffers that are not opened.  Additionally, each succeeding workspace includes the buffer in the previous workspaces, even if they were not included before saving the desktop.

This is what happens (the first/leftmost buffer is the visible buffer):

Before using desktop-save and desktop-revert:
- Workspace 1: *scratch*
- Workspace 2: test.org, *scratch*
- Workspace 3: test.el, random.org, dired, *scratch*

After using desktop-save, quitting emacs, and using desktop-revert:
- Workspace 1: *scratch*
- Workspace 2: test.org, *scratch*
- Workspace 3: test.el, test.org, *scratch*

Is integration with desktop saving planned or possible? Since tabspaces work with builtin packages. I've tried it with burly.el too and similar problems persist.

--

Another thing, though I am not sure if I must open another issue for it:  tab-bar-detach-tab and tab-bar-move-tab-to-frame has issues such that when a workspace is moved to another frame, deleting it with tabspaces-kill-buffers-close-workspace still acts as if it wasn't moved to another frame, and using the function repeatedly removes the buffers in the workspaces in the frame where the moved workspace came from.

**Comment by mclearc** [comment]
I'd certainly like to see Tabspaces work with desktop.el so I'll have to run some tests and see what's going on. Does desktop-save automatically save all buffers or only some (e.g. ignoring dired buffers for example)? Anyways I'll experiment and report back.

**Comment by mclearc** [comment]
As for the second issue I'm not sure if there is an easy fix as the buffer lists are set with respect to particular frames. Moreover, one of the virtues of Tabspaces (at least for me) is that it obviates the need for a multi-frame workflow. But feel free to open a new issue and I'll see what I can figure out when I have more time.

**Comment by appleinario** [comment]
> I'd certainly like to see Tabspaces work with desktop.el so I'll have to run some tests and see what's going on. Does desktop-save automatically save all buffers or only some (e.g. ignoring dired buffers for example)? Anyways I'll experiment and report back.

I am using desktop+ (https://github.com/ffevotte/desktop-plus), so I am not entirely sure if the result is 1-to-1 with desktop.el only, but in my experience, it saved dired buffers, open frames, window configuration, while it ignored *Messages*, *scratch*, and neotree buffers.

--

As for the second issue, it's not really big of a deal since I don't really work with multiple frames, but it is something that I have observed. Maybe better for someone else open a new issue if there is a growing need.

**Comment by mclearc** [comment]
Hi @appleinario -- I've added *very* basic session management for tabspaces (note that this is separate from desktop.el functionality). Basically you can save and restore all tabs and buffers. See commit https://github.com/mclear-tools/tabspaces/commit/20df83ed43214b7e0feb9a03f63b0d5de21d6b66 for details. 

But basically, if you set `tabspaces-session` to `t` it will add a hook that automatically save the open tabs and buffers when quitting. You can restore them with `tabspaces-restore-session` or set `tabspaces-session-auto-restore` to `t` to have them restored on next startup. Let me know what you think, whether it works for you (I haven't tested extensively), and whether there is core functionality that is missing (probably).
