### ISSUE TITLE
error while installing from melpa

### ISSUE THREAD

**Issue by JonatanSahar** [mclear-tools/tabspaces#22]
Hi,
I get the following when installing trough `package-install`:

```
In tabspaces-switch-buffer-and-tab:
tabspaces.el:322:25: Error: ‘add-to-list’ can’t use lexical var ‘tabcand’; use
    ‘push’ or ‘cl-pushnew’

```

although somehow installation proceeds..

**Comment by mclearc** [comment]
Thanks! Should be resolved by https://github.com/mclear-tools/tabspaces/commit/68f3bf8300996b5ede3fc2e423332a9e90c67bb5
