### ISSUE TITLE
Searching files in a workspace

### ISSUE THREAD

**Issue by zetashift** [mclear-tools/tabspaces#23]
Hi! Thank you for the great plugin. It's exactly the simplicity I was looking for.
I'm only missing one thing, and that is a command/function that searches through the current project(starting from the defined root and N folders deep), while respecting .gitignore.

I don't think this needs to be a function for tabspaces, but I'm new in Emacs-land and I was wondering what would be the best way.

**Comment by mclearc** [comment]
I think the most straightforward option is to use `project-find-file`. That's a built in function. If you need to search within files use grep or ripgrep, perhaps via `consult-grep/ripgrep` if you use consult.

**Comment by ParetoOptimalDev** [comment]
> I think the most straightforward option is to use `project-find-file`. That's a built in function. If you need to search within files use grep or ripgrep, perhaps via `consult-grep/ripgrep` if you use consult. 

There is also `project-find-regexp`. I also find it useful you can get help in the middle of typing a prefix for something like the project prefix `C-x p` by adding `C-h`. So in full that is `C-x p C-h`, but in practice it's usually typing `C-x p` and thinking "what was that binding again?" then typing `C-h`.

With consult it even provides a selection menu!

**Comment by zetashift** [comment]
I absolutely had no idea about those project specific built-in commands!

Thank you that is awesome :D
