### ISSUE TITLE
`tabspaces-session-auto-restore t` doesn't autorestore when switching to project 

### ISSUE THREAD

**Issue by zetashift** [mclear-tools/tabspaces#24]
So whenever I want to switch to a project using `tabspaces-open-or-create-project-and-workspace` I would like it to auto restore the session. But currently that is not happening.

- `tabspaces-mode` seems to be enabled on startup
- Manually invoking `tabspaces-restore-session` loads the buffers I expect
- Currently whenever I `open-or-create-project-and-workspace` I only get a `find file` pop up to find files in the project.

### config

My current config for tabspaces using [elpaca](https://github.com/progfolio/elpaca):
```elisp
(use-package tabspaces
  :ensure t
  :hook (emacs-startup . tabspaces-mode)
  :commands (tabspaces-switch-or-create-workspace
             tabspaces-open-or-create-project-and-workspace)
  :custom
  (tabspaces-keymap-prefix "C-c p")
  (tabspaces-use-filtered-buffers-as-default t)
  (tabspaces-include-buffers '("*scratch*"))
  (tabspaces-default-tab "Home")
  ;; sessions
  (tabspaces-session t)
  (tabspaces-session-auto-restore t))

(provide 'init-project)
```

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1857826/218244706-83bd4e59-0edb-46f4-8d16-c139b4c7fe58.png">

**Comment by mclearc** [comment]
Right now session restore only works by loading the file, typically at startup. I might include this functionality in a future release though.

**Comment by mclearc** [comment]
I've added some new session project restoration capability. Please look at the readme and commit 2aa9b33f29b435bea6c6fa37aa14873b6ab153aa

**Comment by zetashift** [comment]
Oh very nice! Thank you :D.

Reading through the readme changes, it seems that I don't have to do anything if because `tabspaces-open-or-create-project-and-workspace` should just automatically restore the last session right?

Currently when I call that command I still get the "find file in project" pop-up, instead of the tabs being restored.

**Comment by mclearc** [comment]
Did you save a project session?__Colin McLearcolinmclear.netOn Feb 13, 2023, at 7:29 PM, zetashift ***@***.***> wrote:﻿
Oh very nice! Thank you :D.
Reading through the readme changes, it seems that I don't have to do anything if because tabspaces-open-or-create-project-and-workspace should just automatically restore the last session right?
Currently when I call that command I still get the "find file in project" pop-up, instead of the tabs being restored.

**Comment by zetashift** [comment]
> Did you save a project session?

Yes, I did, but I used `tabspaces-save-current-project-session` and not `save-session`

**Comment by mclearc** [comment]
Hmm. If there is a project session file and you open the project with open-or-create project it should find it. If not can you open a new issue with more details?__Colin McLearcolinmclear.netOn Feb 13, 2023, at 7:49 PM, zetashift ***@***.***> wrote:﻿

Did you save a project session?

Yes, I did, but I used tabspaces-save-current-project-session and not save-session

**Comment by zetashift** [comment]
I'll try to get a minimal repro going, thank you for your time!
