### ISSUE TITLE
question about your README

### ISSUE THREAD

**Issue by mtk** [mclear-tools/tabspaces#27]
you wrote "Calling the minor-mode tabspaces-mode sets up newly created tabs as buffer-isolated workspaces using tab.el in the background".  what is a 'buffer-isolated workspace'?

**Comment by mclearc** [comment]
In other words -- buffers that are specific to a tab. Basically, tabspaces allows you to keep buffers grouped with their tab and not with another tab (so, eg. your agenda buffer doesn't show in your project tab buffer list)

**Comment by mtk** [comment]
sorry, still confused.  buffers are displayed in windows.  windows are
displayed in a tab (tab frame?).  a single tab can optionally display many
windows simultaneously.  and a strip of tabs is displayed in a frame.  what
constraint/policy does tabspaces impose over this hierarchy?  /mark

**Comment by ParetoOptimalDev** [comment]
@mtk Maybe I can word it differently and it'll help.

With tabspaces your buffer list gets filtered to buffers you opened while in that tab. If I have two tabs T1 and T2 and switch to a new buffer *newbuf* while on T2 then when I switch back to T1 I will not see *newbuf*.

**Comment by mtk** [comment]
ah, very clear.  thanks!  /mark
