### ISSUE TITLE
C-c TAB b to switch buffers always lists the current buffer at the top of the list

### ISSUE THREAD

**Issue by jeffbowman** [mclear-tools/tabspaces#28]
This is different from how Emacs does buffer switching by default, which is to not list the current buffer in the list of candidates at all.  This screenshot shows the behavior I'm describing.  The default local buffer to switch to should not be the current buffer, but instead (in this case) it should be `cus-edit.el.gz` instead. 

![image](https://user-images.githubusercontent.com/20442/223500511-4f6d1b90-7c26-4f4d-b449-9764af9de662.png)

**Comment by mclearc** [comment]
Let me know if that doesn't work!

**Comment by jeffbowman** [comment]
Thanks!  Works perfectly!
