### ISSUE TITLE
when switching buffer and tab to an existing buffer, it gets added to the current tabspace

### ISSUE THREAD

**Issue by JonatanSahar** [mclear-tools/tabspaces#29]
Hi, great package!

If I'm in a tabspace and I open a buffer that's already opened in another tabspace, and I've specified I want to switch to its tab (using `tabspaces-switch-buffer-and-tab`), I expect the buffer not to be added to the current tab as well - or to be prompted if I want to deliberately add it. 
With time, this totally defeats the point of segregating buffers between tabs, in my opinion. 

Thanks!

**Comment by JonatanSahar** [comment]
my bad, I didn't use `tabspaces-switch-buffer-and-tab` correctly.

**Comment by JonatanSahar** [comment]
is there a way to make it use `consult-buffer`?

**Comment by mclearc** [comment]
> is there a way to make it use `consult-buffer`?

Yep -- see https://github.com/mclear-tools/tabspaces#consult
