### ISSUE TITLE
Add tabspaces-session-file to no-littering

### ISSUE THREAD

**Issue by gokuldas** [mclear-tools/tabspaces#33]
I have submitted [a PR](https://github.com/emacscollective/no-littering/pull/213) to the [no-littering](https://github.com/emacscollective/no-littering) emacs package to include configuration of tabspaces' `tabspaces-session-file` variable.

No-littering package is an attempt to keep `user-emacs-directory` and source directories tidy by assigning standard locations for data and config files. The files and directories are also expected to follow [certain naming conventions](https://github.com/emacscollective/no-littering#conventions).

In addition to informing you, I hope you can confirm that this is the only data file saved by tabspaces.

Thanks!

PS: A discussion thread would have been more appropriate for this. Please feel free to close this issue.

**Comment by mclearc** [comment]
Thanks very much for this. And yes -- the sessions file is the only data file saved by tabspaces.
