### ISSUE TITLE
Rename created tabspace

### ISSUE THREAD

**Issue by logc** [mclear-tools/tabspaces#37]
Once you have created a tabspace, is there a way to rename it? Specially, I would want to rename the first tabspace created in a session. 

It tends to stay with the name of the first buffer within it, while on creating the rest of tabspaces I can pick a name that is meaningful to the tasks I intend to solve in it.

**Comment by logc** [comment]
Thanks for this package, it is the nicest solution to having tabs while re-using standard mechanisms!

**Comment by mclearc** [comment]
Thanks -- I'm glad you've found it useful. Tabspaces just uses the built-in functionality of tab-bar to rename tabs. So the command you're looking for is `tab-bar-rename-tab-by-name` (there are some other tab-bar renaming functions but that is probably the one you want).
