### ISSUE TITLE
[BUG] two projects with same name are considered as one workspace

### ISSUE THREAD

**Issue by abougouffa** [mclear-tools/tabspaces#38]
Hello,

Let's say that I have two projects at:

`~/ws/proj1`
`~/ws/oldstuff/proj1`

Opening the first project with `tabspaces` will create a `proj1` tab. When opening the second one, it will consider that the project doesn't change and uses the same `proj1` tab.

As the directories aren't the same, it should rather create another tab with something like `proj1<1>` or `oldstuff/proj1`.

Thank you for this package!

Regards

**Comment by mclearc** [comment]
sorry for the slow reply on this -- will try and get a fix pushed this weekend
