### ISSUE TITLE
[SUGGESTION] Don't overwrite `project-switch-commands`

### ISSUE THREAD

**Issue by ghost** [mclear-tools/tabspaces#40]
I didn't really know if I could figure out where in the code Tabspaces gets its current behavior since I don't know Emacs Lisp that well. But then I remembered the words of Kant that "I have no knowledge of myself as I am, but merely as I appear to myself." and tried anyway.

I noticed that if I follow these steps:
1. <kbd>M-x</kbd> `tabspaces-open-or-create-project-and-workspace`
2. Hover over a project from the `project--list` (it has to be a project that doesn't have an existing tabspace yet)
3. Hit enter

... then Tabspaces will always run `project-find-file`. This behavior is hardcoded here: https://github.com/mclear-tools/tabspaces/blob/main/tabspaces.el#L392

I was wondering - would it make sense to allow users to provide their own function in place of `project-find-file`? That way, they could have e.g. `magit-status` be called instead of `project-find-file`.

Off the top of my head, the customization could come in the form of a new `tabspaces-project-switch-commands` variable in place of the hardcoded `project-find-file`.

On the other hand, it could potentially be more beautiful if `project-switch-commands` were never set to just `project-find-file`, and the unchanged value of `project-switch-commands` was used (so the project.el minibuffer prompt appears asking "what do you wanna do with this"). That way, the customization would just come from the default behavior of project.el

**Comment by ParetoOptimalDev** [comment]
> it could potentially be more beautiful if project-switch-commands were never set to just project-find-file, and the unchanged value of project-switch-commands was used (so the project.el minibuffer prompt appears asking "what do you wanna do with this"). That way, the customization would just come from the default behavior of project.el

Re-using the users default configuration for project.el seems like a good thing here to me.

**Comment by mclearc** [comment]
thanks both -- I'll try and make some fixes this weekend
