### ISSUE TITLE
Unusable `tabspaces-open-or-create-project-and-workspace`

### ISSUE THREAD

**Issue by abougouffa** [mclear-tools/tabspaces#42]
Hello and thank you for your responsiveness on issue #38 

The commit e93774372b8e860a9cb092b27a4ae3c482323608 broke the workflow! Now, calling `tabspaces-open-or-create-project-and-workspace` on **existing** projects asks each time for repo initialization as Git, Hg, ...

Also, the `tabspaces--generate-unique-tab-name` function causes opening the **same** project twice to create two tabs with names "project" and "project<1>".

I think the commit should be revoked until this gets fixed, in my config, I'm explicitly using the commit before this one.

I will try to work on this the next weekend and open a PR.

Thank you again for this awesome package!

**Comment by mclearc** [comment]
Ah -- ok now I think I see the problem. When I have `(setq tabspaces-project-switch-commands project-switch-commands)` I see the vc initialization pop up. This doesn't happen if I specify e.g. `project-find-file`. I'll look into it.

**Comment by mclearc** [comment]
Turns out this was just a dumb error on my part -- I had duplicated the function erroneously.

**Comment by abougouffa** [comment]
Thank you for the quick response, I've noticed and fixed it, but you were much faster! Thanks again!
