### ISSUE TITLE
Switch between tabspaces

### ISSUE THREAD

**Issue by smalltimer** [mclear-tools/tabspaces#49]
Hi, 

I am trying to create a function which switches to the previously opened tabspace.

Suppose I have multiple tabspaces open (say, A,B,C). I am in A, and then navigate the tabspaces in the sequence A -> B -> C. I would like to make a function that switches from the current tabspace (C) to the previous one (B). Invoking this function twice in succession from C, would bring me back to C.

Any tips would be awesome. Sorry, this is not an issue, but I didn't know where else to reach out.

Cheers

**Comment by mclearc** [comment]
This should be already built into tab-bar.el:

```emacs-lisp
;; Defined in /Applications/Emacs.app/Contents/Resources/lisp/tab-bar.el
(defun tab-bar-switch-to-recent-tab (&optional arg)
  "Switch to ARGth most recently visited tab.
Interactively, ARG is the prefix numeric argument and defaults to 1."
  (interactive "p")
  (unless (integerp arg)
    (setq arg 1))
  (let ((tab-index (tab-bar--tab-index-recent arg)))
    (if tab-index
        (tab-bar-select-tab (1+ tab-index))
      (message "No more recent tabs"))))
  ```

**Comment by smalltimer** [comment]
Thank you for your kind and patient reply. Not sure how I missed this !
