### ISSUE TITLE
Question about tabspaces-exclude-buffers

### ISSUE THREAD

**Issue by samb233** [mclear-tools/tabspaces#50]
After [929e677](https://github.com/mclear-tools/tabspaces/commit/929e6772ce87a049f2a05cce26071adbe741e60e), the default behavior of creating new tabs has changed. When creating a new tab, all the buffers in current tab would be kept in the new tab as these buffers are not in `tabspaces-exclude-buffers`. 
https://github.com/mclear-tools/tabspaces/blob/beab19358c9640493ab01bed8f7c1782b131357e/tabspaces.el#L133-L138
Is this behavior designed to be like this? Or would it be better to use `and` condition with line 137-138?

**Comment by mclearc** [comment]
Fixed - Thank you!
