### ISSUE TITLE
Displays *Messages* buffer

### ISSUE THREAD

**Issue by seagle0128** [mclear-tools/tabspaces#54]
Hi, thanks for the great package! I am enjoying it, and it was integrated into [Centaur Emacs](https://github.com/seagle0128/.emacs.d).

I have a quick question: How to display the "*Messages*" buffer in all workspaces? I tried customizing `tabspaces-include-buffers` but seems not working. What was I missing?

**Comment by mclearc** [comment]
Glad to hear you find it useful! You would just do this:

`(setopt tabspaces-include-buffers '("*scratch*" "*Messages*"))`

**Comment by seagle0128** [comment]
> (setopt tabspaces-include-buffers '("*scratch*" "*Messages*"))

It doesn't work when "*Messages" is buried, but it's displayed in all buffers (narrow via `< b`).

**Comment by mclearc** [comment]
Hmm -- all I can report is that when I have tested it, it works (i.e. without narrowing -- any new project/tabspace includes *Messages*). Have you already tried it with `emacs -q` ?

**Comment by dalugm** [comment]
Looks like the same problem as mine...

https://github.com/mclear-tools/tabspaces/pull/46#issue-2009054622

**Comment by dalugm** [comment]
> > Looks like the same problem as mine...
> > [#46 (comment)](https://github.com/mclear-tools/tabspaces/pull/46#issue-2009054622)
> 
> Thank you, @dalugm !
> 
> They are exactly same. But the solution doesn't work when the new workspace is created.
> 
> Is it possible to change `tabspaces--local-buffer-p` or something else? My workaround:
> 
> ```emacs-lisp
> (setq tabspaces-include-buffers '("*scratch*" "*Messages*"))
> (defun tabspaces--local-buffer-p (buffer)
>       "Return whether BUFFER is in the list of local buffers."
>       (or (member (buffer-name buffer) tabspaces-include-buffers)
>           (memq buffer (frame-parameter nil 'buffer-list))))
> ```

Cool! I find this patch works more solid than current solution, maybe we can merge this?

**Comment by seagle0128** [comment]
> Cool! I find this patch works more solid than current solution, maybe we can merge this?

@dalugm @mclearc I've committed a PR.

**Comment by mclearc** [comment]
Merged! Thanks :)
