### ISSUE TITLE
Mixing tabspaces-switch-to-buffer with tab-bar-select-tab leaks buffer to another tab

### ISSUE THREAD

**Issue by krisman** [mclear-tools/tabspaces#56]
I have been using this excellent package daily for around a year, but I eventually need to stop to clean up tabs because they end up with unrelated buffers.  Today, I started investigating a bit more and realized  it happens when I'm quickly alternating between  buffers and tabs:

If I do:
- C-x tabspaces-switch-to-buffer 
 (prompt opens, asking for a buffer)
- C-x tab-bar-select-tab  
- \<enter\> to load default entry.

The buffer list will be loaded from the old tab, but the switch-to-buffer will happen in the new tab.  

For sure, this is user error.  But can we make the interface a bit more friendly?  

ideally,  the minibuffer would be per-tab, but that's quite hard/impossible.   A simpler solution would be exiting the minibuffer when switching tabs, but that is not very emacsy.  I think we could at least detect the tab changed during tabspaces-switch-to-buffer and error out.  Alternatively, we could force the switch to happen in the old tab/window where the command was initiated.  Thoughts?

**Comment by mclearc** [comment]
Sorry to not respond sooner. I haven't quite been able to reproduce this. Is the idea that you think we should be trying to error out in cases where the user runs a command from the mini buffer while in the middle of another command?  I'm not sure that there is any way to accommodate this kind of situation without making the code more complex than I would like. In general the aim of tabspaces is to do as much with the built-in tab-bar and project packages, and avoid any further complexity where possible.

**Comment by krisman** [comment]
> Sorry to not respond sooner. I haven't quite been able to reproduce this. Is the idea that you think we should be trying to error out in cases where the user runs a command from the mini buffer while in the middle of another command? I'm not sure that there is any way to accommodate this kind of situation without making the code more complex than I would like. In general the aim of tabspaces is to do as much with the built-in tab-bar and project packages, and avoid any further complexity where possible.

So, the problem is that I end up losing the nice separation of buffers provided by tabspaces if I happen to switch tab amid a tabspaces-switch-to-buffer operation.  The problem, as far as I understand it, is that the current-tab might change between the time we read the tabspaces-buffer-list to generate the completion list for read-buffer  inside tabspaces-switch-to-buffer and the time that we actually execute switch-to-buffer.  In this case, we switch to a buffer from the old tab , but open it in a new tab, adding it to that tabspace accidently.  Is there a way to enroll the entire function in a "with-current-tab"-like operation?

I don't have a smart way to fix it, to be honest.  The best I could come up with was to kill the command if I detect the minibuffer is running when I switch tabs:

```
(defun gkb/tab-bar-select-tab-no-minibuffer (&optional tab-number)
  (let ((minibuffer (active-minibuffer-window)))
    (if minibuffer
	(with-selected-window minibuffer
	  (minibuffer-keyboard-quit)))))
(advice-add 'tab-bar-select-tab :before #'gkb/tab-bar-select-tab-no-minibuffer)
```

It is a silly hack and outside of tabspaces, but happens to work fine for me.  Feel free to close the issue if you don't see a better solution.

**Comment by mclearc** [comment]
Thanks for the additional info @krisman -- and I appreciate the suggested hack. I think that the edge case you're describing here is one I'm not going to design around but at least there your suggested code should anyone else have similar issues. And if it becomes enough of a pain point for people perhaps I'll revisit it in the future.
