### ISSUE TITLE
Is it possible to create workspaces based on modes?

### ISSUE THREAD

**Issue by zhenhua-wang** [mclear-tools/tabspaces#57]
Hi, Thanks for this great package, this is so useful!

I wonder if there is way to  create workspaces based on modes? For example, besides from having projects in different workspaces, I would also like to keep all *help* buffers on a different workspace, and all magit buffers on another workspace.

**Comment by zhenhua-wang** [comment]
Support moving buffer to another tabspace might be an easy solution to this. With this, I can move relevant buffers to a single tab (e.g. "Help") in relevant buffer-hooks

**Comment by mclearc** [comment]
You can also look into the display buffer list. For example, here's how I group all my email buffers:

```emacs-lisp

(setq display-buffer-base-action nil)

(add-to-list 'display-buffer-alist
             `("\\*mu4e-main\\*"
               (display-buffer-in-tab)
               (tab-name . "Email")))
(add-to-list 'display-buffer-alist
             `("\\*mu4e-view\\*"
               (display-buffer-in-tab)
               (tab-name . "Email")))
(add-to-list 'display-buffer-alist
             `("\\*mu4e-headers\\*"
               (display-buffer-in-tab)
               (tab-name . "Email")))
(add-to-list 'display-buffer-alist
             '(cpm-display-buffer-email-managed-p
               (display-buffer-in-tab
                display-buffer-reuse-mode-window)
               (tab-name . "Email")))
               
```

**Comment by mclearc** [comment]
Also -- you can use `(tabspaces-switch-or-create-workspace)` along with whatever hook you have for relevant modes, depending on what you're trying to accomplish (e.g. having a "markdown" tab and using `(tabspaces-switch-or-create-workspace)` to switch to the 'markdown' tab whenever a markdown mode file is opened.

**Comment by zhenhua-wang** [comment]
Wow, both methods sounds great to me. Thanks for the help.
