### ISSUE TITLE
"Bury-buffer" alse removes the buffer from current tab

### ISSUE THREAD

**Issue by zhenhua-wang** [mclear-tools/tabspaces#58]
I found that calling `bury-buffer` on a buffer will also remove that buffer from the current tab (`(tabspaces--buffer-list)`). Is this a bug or by design?

**Comment by mclearc** [comment]
Hi -- this is intentional. The buffer is still on that all buffers list but just no longer listed in the given tabspace. If you'd like to see this behave differently as an option I'm happy to look at a pull request.

**Comment by zhenhua-wang** [comment]
Thank you for clarifying! I will look into this in detail later.
