### ISSUE TITLE
help understanding buffer-isolated tabspaces

### ISSUE THREAD

**Issue by titaniumbones** [mclear-tools/tabspaces#7]
I'm just trying to figure out if this package will work for me and wanted to run a couple of scenarios by you.  

- I'm working in a project in one tab.  I realize I need to do something in another project.  I select the relevant buffer or file with `tabsapces-switch-to-buffer` (can I even do that?). Does the buffer open for me in the appropriate tab for its own project? 

- I have one tab that I use for mail, using mu4e.  mu4e creates a bunch of its own buffers, and I also have a dashboard buffer on the side (using `mu4e-dashboard`). When I create the workspace for this tab, can I specify that all of those buffers should be included in the workspace filtered buffer list? That is, can I specify my own pseudo-project that holds things like mail, rss feeds, etc? 
- 

Maybe the answers to these questions are obvious, but I didn't immediately see how to do them when I looked at the code.

Thank you!

**Comment by mclearc** [comment]
Thanks for your questions. The project as currently stands is pretty dead simple. It just provides a filtered buffer list for the current tab and some help functions for opening projects in workspaces. As for your two use cases, let me see if I can help. You add a buffer to a tab/workpace by simply opening it in the tab. So tabs are themselves indifferent to which project(s) are open in them, or even whether you have multiple projects open in them. If you want to open a project in its own tab use `tabspaces-open-existing-project-and-workspace`. If you just want to open a project in a tab that already exists and has other buffers you want to keep you would just use `project-switch-project` (or you could use my `project-switch-project-open-file` if you want to skip `project.el`'s interactive menu). 

Your second case is such that you needn't specify the buffers -- remember all you need to do to add a buffer to a tab/workspace is simply open it in the tab/workspace. So, for example, I have this function to open my email tabspace:

```emacs-lisp
(defun cpm/open-email-in-workspace ()
  "Open mu4e email in its own workspace"
  (interactive)
  (if (member "Email" (tabspaces--list-tabspaces))
      (progn
        (tab-bar-switch-to-tab "Email")
        (cond ((get-buffer "*mu4e-headers*")
               (switch-to-buffer "*mu4e-headers*"))
              ((get-buffer " *mu4e-main*")
               (progn
                 (switch-to-buffer " *mu4e-main*")
                 (delete-other-windows)))
              (t (mu4e))))
    (progn
      (tabspaces-create-workspace)
      (tab-bar-rename-tab "Email")
      (require 'org) 
      (find-file (concat org-directory "mail.org"))
      (mu4e)
      (switch-to-buffer " *mu4e-main*"))))

(bind-key* "s-5" 'cpm/open-email-in-workspace)
``` 

If you want separate tabs for mail, rss, etc., but also want them all grouped within one overarching tab you want to use [tab-groups](https://git.savannah.gnu.org/cgit/emacs.git/commit/etc/NEWS?id=f9b737fb9d21ac7adff403274167e76e77d033b8). There's a related package for this: https://github.com/fritzgrabo/tab-bar-groups. I think that should work with tabspaces but I haven't tested it extensively. I'm hoping to more clearly accommodate tab-groups in the future.

**Comment by mclearc** [comment]
I'm going to close this but please feel free to comment or reopen if you have further questions.
