### ISSUE TITLE
tabspaces-switch-to-or-create-workspace creates two tabs

### ISSUE THREAD

**Issue by aaronjensen** [mclear-tools/tabspaces#8]
`tabspaces-switch-to-or-create-workspace` invokes both `tabspaces-create-workspace` and `tab-bar-new-tab`, which creates two tabs.

**Comment by mclearc** [comment]
thanks, looks like I didn't clean up the old code when I was reworking the code -- will fix that in a minute.

**Comment by mclearc** [comment]
Closed by 383b3b6d5c95efc7677056137da2ef880bf67b56

**Comment by aaronjensen** [comment]
Thanks for the quick fix!
