### ISSUE TITLE
tabspaces-open-existing-project-and-workspace includes current buffer in new workspace

### ISSUE THREAD

**Issue by aaronjensen** [mclear-tools/tabspaces#9]
`tabspaces-create-workspace` will include the current buffer in the newly created workspace. This means that `tabspaces-open-existing-project-and-workspace` includes it as well. In my custom command, I have to remove it with `tabspaces-remove-selected-buffer`:

```el
(defun aj/tabspaces-switch-project (project-to-switch)
    "Switch to project tab and find project file.
Only if the switched to buffer is not of that project."
    (interactive (list (project-prompt-project-dir)))

    (let* ((tab-names (mapcar (lambda (tab) (alist-get 'name tab)) (funcall tab-bar-tabs-function)))
           (project-name (aj/project-name project-to-switch))
           (tab-name project-name)
           new-tab)
      (if (member tab-name tab-names)
          (tab-bar-select-tab-by-name tab-name)
        (setq new-tab t)
        (tabspaces-create-workspace)
        (tab-bar-rename-tab tab-name))
      (unless (string= project-name (aj/project-name))
        (let ((default-directory project-to-switch)
              (previous-buffer (current-buffer)))
          (project-find-file)
          (when new-tab
            (tabspaces-remove-selected-buffer previous-buffer))))))
```

**Comment by mclearc** [comment]
I think this is a function of how you set `tab-bar-new-tab-choice`. I have mine set to the scratch buffer. But if it is set to `t` then this is what happens:

> If t, start a new tab with the current buffer, i.e. the buffer
that was current before calling the command that adds a new tab
(this is the same what make-frame does by default).

If that is what is going on here I'm not sure I want to make any changes in the code since I don't want to conflict with people's tab settings etc. But I can put something in the README about it. Can you try it with something other than `t` set and see if that fixes the issue?

**Comment by aaronjensen** [comment]
Ah, yes, I do have that set to `t`. It works as you described. I can make use of that in my function. Thanks.

**Comment by mclearc** [comment]
Great - thanks for raising the issue though. I'll put a note in the docs about this setting.

**Comment by aaronjensen** [comment]
Hm, seems it is not so straight forward when using this, it does not include the current buffer initially in the buffer list. It gets there eventually. I wonder if the current buffer should be included within `tabspaces-create-workspace`? If so, you might consider doing:

```el
(defun tabspaces-open-existing-project-and-workspace ()
  "Open an existing project as its own workspace."
  (interactive)
  (let ((tab-bar-new-tab-choice (lambda () (call-interactively #'tabspaces-project-switch-project-open-file))))
    (tabspaces-create-workspace))
  (tab-bar-rename-tab (tabspaces--name-tab-by-project-or-default)))```

**Comment by mclearc** [comment]
Interestingly, this function doesn't work well for me (i.e. it doesn't show the buffer picked with `tabspaces-project-switch-project-open-file` initially in the buffer list, though it does open that buffer correctly). The old function works perfectly well. I suspect this may also be just a consult problem since the buffer list seems to update just using `tabspaces-switch-to-buffer`.

**Comment by aaronjensen** [comment]
I don't think it's a consult problem. I think it doesn't get added to the buffer list until it is switch away from and it is filtered out by `tabspaces-create-workspace`. Try this:

```el
(defun tabspaces-create-workspace (&optional arg)
  "Create a new tab/workspace with cleaned buffer lists.

ARG is directly passed to `tab-bar-new-tab'. Only buffers in
`tabspaces-include-buffers' are kept in the `buffer-list' and
`buried-buffer-list'."
  (interactive)
  (tab-bar-new-tab arg)
  ;; https://www.gnu.org/software/emacs/manual/html_node/elisp/Current-Buffer.html
  ;; The current-tab uses `buffer-list' and `buried-buffer-list'.
  ;; A hidden tab keeps these as `wc-bl' and `wc-bbl'.
  (set-frame-parameter nil
                       'buffer-list
                       (seq-filter (lambda (buffer)
                                     (or (eq buffer (current-buffer))
                                         (member (buffer-name buffer)
                                                 tabspaces-include-buffers)))
                                   (frame-parameter nil 'buffer-list)))
  (set-frame-parameter nil
                       'buried-buffer-list
                       (seq-filter (lambda (buffer)
                                     (member (buffer-name buffer)
                                             tabspaces-include-buffers))
                                   (frame-parameter nil 'buried-buffer-list))))
```

**Comment by aaronjensen** [comment]
The previous method only works coincidentally because your `tab-bar-new-tab-choice` happens to be in your `tabspaces-include-buffers`.
